#include <MK64F12.h>
#include "utils.h"
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
//#include "games.h"
#include "uart.h"
int p1_score = 0; // score for the first player
int p2_score = 0; // score for the second player
int game_chosen = 0; // game_chosen is 1 when the game is chosen
int game = 0;        // game number choosen by the player
int right_choice = 1;  // correctly choosen color used to decide if the player clicked button on the right led
int color = 1;         // color is used to flash led depending on the value of the color
realtime_t current_time = {0,0};  //initializing the current time
realtime_t start;         // start is used to compare the current time and the time when the button is clicked
int milisec = 20970;  //approximate milisec
// p1_correct and p2_correct are used for game 4, if p1 chooses the right sequence p1_correct is 1 similarly if p2 chooses the right sequence p2 is 1 
int p1_correct = 0; 
int p2_correct = 0;

// following variables are used to make sure that the players are not trying to cheat by pressing everytime in game 4
int p1_pressright = 1; 
int p2_pressright = 1;

// setting up the PITtimer for the current time
void timer_start(void) {
	NVIC_EnableIRQ(PIT0_IRQn);
	SIM->SCGC6 |= SIM_SCGC6_PIT_MASK;
	PIT->MCR = 0;
	PIT->CHANNEL[0].LDVAL = milisec;
	PIT->CHANNEL[0].TFLG  = 1; // resets timer flag
	PIT->CHANNEL[0].TCTRL = 3; // enabling the interrupt
}

// PIT0 IRQHandler is used to set interrupt for current time to be updated every mili seconds
void PIT0_IRQHandler(void)
{
	PIT->CHANNEL[0].TCTRL = 1; // disabling the interrupt 
	current_time.msec++;
	if(current_time.msec == 1000)
		{
			current_time.msec = 0;
			current_time.sec++;
		}
	PIT->CHANNEL[0].TFLG = 0x1; // reset the flag
	PIT->CHANNEL[0].TCTRL = 3; // enabling the interrupt
}

// PORTC iIRQ handler is used to handle the interrupt generated by SW2
void PORTC_IRQHandler(void){
		if (game_chosen == 0 )
			game++; // game is not chosen yet so increment game to find the game number
		else {
			if ( right_choice == 1) {
				if (game/2 == 4) p1_correct = 1;
				int time_diff;
				if (current_time.msec > start.msec)
					time_diff = (current_time.sec - start.sec)*1000 + (current_time.msec - start.msec);
				else 
					time_diff = (current_time.sec - start.sec)*1000 - (start.msec - current_time.msec );
				if ( time_diff < 500 )
					p1_score++;
			}
			else {
				if (game/2 == 4) 
					{p1_correct = 0;
					 p1_pressright = 0;}
				if ( p1_score > 0 ) 
					p1_score--;
			}
		}
	  PORTC->PCR[6] |= (1<<24); // clear interrupt status flag	  
}

void PORTA_IRQHandler(void){
		if ( right_choice == 1) {
			if (game/2 == 4) p2_correct = 1;
			int time_diff;
			if (current_time.msec > start.msec)
				time_diff = (current_time.sec - start.sec)*1000 + (current_time.msec - start.msec);
			else 
				time_diff = (current_time.sec - start.sec)*1000 - (start.msec - current_time.msec );
			if ( time_diff < 500 )
				p2_score++;
		}
		else {
			if (game/2 == 4) 
				{p2_correct = 0;
				 p2_pressright = 0;}
			if ( p2_score > 0 ) {
				p2_score--;
			}
		}
	  PORTA->PCR[4] |= (1<<24); // clear interrupt status flag
}




/* Main function */
int main(void) {
	LED_Initialize();
  switch_setup();
	uart_init(); // initializing uart
	uart_put("choose a game by pressing sw2 button \n\r");
	uart_put("press 1 times for game 1. press 2 times for game 2 \n\r");
	uart_put("press 3 times for game 3. press 4 times for game 4 \n\r");
	uart_put("\n\r");
	// choose game
	int seed =0;
	while(game==0){
		seed++;
	}
	for (int i=0; i<16;i++) {
		delay();
	}
	srand(seed);
	timer_start();
	p1_score = 0;
	p2_score = 0;
	game_chosen = 1;
	// game 1 starts here
	if (game/2 == 1) {
		uart_put("game 1 is chosen \n\r");
		uart_put("\n\r");
		int total = 10;
		while(total > 0) {
			int ran_num = rand() % 10 + 1;
			for (int i = 0; i < ran_num; i++ ) {
				delay();
			}
			LEDRed_On();
			start.sec = current_time.sec;
			start.msec = current_time.msec;
			delay();
			LED_Off();
			total--;
		} 
	// white light
	game_break();
	uart_put("player 1's score is ");
	char result[32];
  sprintf(result, "%d", p1_score/2);
	uart_put(result);
	uart_put("\n\r");
	uart_put("player 2's score is ");
  sprintf(result, "%d", p2_score/2);
	uart_put(result);
	uart_put("\n\r");
	}
	// game 2 starts here
	else if (game/2 == 2) {
		uart_put("game 2 is chosen \n\r");
		uart_put("\n\r");
		int total = 5;
		while(total > 0) {
			int ran_num = rand() % 10 + 1;
			for (int i = 0; i < ran_num; i++ ) {
				delay();
			}
			// randomly choose color
			color = rand() % 6 + 1;
			// right choice is 1 if the random color matches color red and used in counting score of players
			if (color == 2) { 
				right_choice = 1;
				total--;
			}
			else right_choice = 0;
			if (color == 1)
				LEDBlue_On();
			else if(color == 2)
				LEDRed_On();
			else if(color == 3)
				LEDYellow_On();
			else if(color == 4)
				LEDTeal_On();
			else if(color == 5)
				LEDPurple_On();
			else
				LEDGreen_On();
			start.sec = current_time.sec;
			start.msec = current_time.msec;
			delay();
			LED_Off();
		} 
		// white light
		game_break();
		uart_put("player 1's score is ");
		char result[32];
		sprintf(result, "%d", p1_score/2);
		uart_put(result);
		uart_put("\n\r");
		uart_put("player 2's score is ");
		sprintf(result, "%d", p2_score/2);
		uart_put(result);
		uart_put("\n\r");
		// this represent score
		LEDRed_Blink_num((p1_score/2));
		delay();
		LEDBlue_Blink_num((p2_score/2));
	}
	// game 3 starts here , first round look for red , second round loook for blue, third round look for green, pink after each round 
	else if (game/2 == 3) {
		uart_put("game 3 is chosen \n\r");
		uart_put("\n\r");
		uart_put("Round 1 has began \n\r");
		uart_put("look for red LED \n\r");
		//round 1 starts here, look for red
		int w = 0;
		int total = 10;
		int color_arr[total];
		check_led(color_arr, total, 2);
		while(total > 0) {
			int ran_num = rand() % 10 + 1;
			multi_delay(ran_num);
			color = color_arr[w];
			if (color == 2) right_choice = 1;
			else right_choice = 0;
			if (color == 1)
				LEDBlue_On();
			else if(color == 2)
				LEDRed_On();
			else if(color == 3)
				LEDYellow_On();
			else if(color == 4)
				LEDTeal_On();
			//else if(color == 5)
			//	LEDPurple_On();
			else
				LEDGreen_On();
			start.sec = current_time.sec;
			start.msec = current_time.msec;
			delay();
			LED_Off();
			total--;
			w++;
		} 
		delay();
		LEDPurple_On();
		multi_delay(3);
		LED_Off();
		uart_put("\n\r");
		uart_put("Round 1 has ended \n\r");
		uart_put("player 1's score is ");
		char result[32];
		sprintf(result, "%d", p1_score/2);
		uart_put(result);
		uart_put("\n\r");
		uart_put("player 2's score is ");
		sprintf(result, "%d", p2_score/2);
		uart_put(result);
		uart_put("\n\r");
		// this represent score
		LEDRed_Blink_num((p1_score/2));
		delay();
		LEDBlue_Blink_num((p2_score/2));
		// second round start will start after white light turns off
		game_break();
		
		// round 2 starts here, look for blue color
		uart_put("\n\r");
		uart_put("Round 2 has began \n\r");
		uart_put("look for blue LED \n\r");
		multi_delay(2);
		w = 0;
		total = 10;
		int color_arr_2[total];
		check_led(color_arr_2, total, 1);
		while(total > 0) {
			int ran_num = rand() % 10 + 1;
			for (int i = 0; i < ran_num; i++ ) {
				delay();
			}
			// randomly choose color , for now have 3 colors only atsustse needs to add more colors
			color = color_arr_2[w];
			if (color == 1) right_choice = 1;
			else right_choice = 0;
			if (color == 1)
				LEDBlue_On();
			else if(color == 2)
				LEDRed_On();
			else if(color == 3)
				LEDYellow_On();
			else if(color == 4)
				LEDTeal_On();
			//else if(color == 5)
			//	LEDPurple_On();
			else
				LEDGreen_On();
			start.sec = current_time.sec;
			start.msec = current_time.msec;
			delay();
			LED_Off();
			total--;
			w++;
		}
		delay();
		LEDPurple_On();
		multi_delay(3);
		LED_Off();
		uart_put("\n\r");
		uart_put("Round 2 has ended \n\r");
		uart_put("player 1's score is ");
		//char result[32];
		sprintf(result, "%d", p1_score/2);
		uart_put(result);
		uart_put("\n\r");
		uart_put("player 2's score is ");
		sprintf(result, "%d", p2_score/2);
		uart_put(result);
		uart_put("\n\r");
		// this represent score
		LEDRed_Blink_num((p1_score/2));
		delay();
		LEDBlue_Blink_num((p2_score/2));
		// second round start will start after white light turns off
		game_break();
		
		// round 3 starts here, look for green color
		// third round starts here
		uart_put("\n\r");
		uart_put("Round 3 has began \n\r");
		uart_put("look for green LED \n\r");
		multi_delay(2);
		w = 0;
		total = 10;
		int color_arr_3[total];
		check_led(color_arr_3, total, 5);
		while(total > 0) {
			int ran_num = rand() % 10 + 1;
			for (int i = 0; i < ran_num; i++ ) {
				delay();
			}
			// randomly choose color , for now have 3 colors only atsustse needs to add more colors
			color = color_arr_3[w];
			if (color == 5) right_choice = 1;
			else right_choice = 0;
			if (color == 1)
				LEDBlue_On();
			else if(color == 2)
				LEDRed_On();
			else if(color == 3)
				LEDYellow_On();
			else if(color == 4)
				LEDTeal_On();
			//else if(color == 5)
			//	LEDPurple_On();
			else
				LEDGreen_On();
			start.sec = current_time.sec;
			start.msec = current_time.msec;
			delay();
			LED_Off();
			total--;
			w++;
		}
		delay();
		LEDPurple_On();
		multi_delay(3);
		LED_Off();
		uart_put("\n\r");
		uart_put("Round 3 has ended \n\r");
		uart_put("player 1's score is ");
		//char result[32];
		sprintf(result, "%d", p1_score/2);
		uart_put(result);
		uart_put("\n\r");
		uart_put("player 2's score is ");
		sprintf(result, "%d", p2_score/2);
		uart_put(result);
		uart_put("\n\r");
		// this represent score
		LEDRed_Blink_num((p1_score/2));
		delay();
		LEDBlue_Blink_num((p2_score/2));
	}
	// game 4 starts here
	else if (game/2 == 4) {
		char result[32];
		uart_put("game 4 is chosen \n\r");
		int seq[100];  // for now have a constant number of sequence
		int len_seq = 0; // number of colors added to the sequence
		int p1_won = 0; 
		int p2_won = 0;
		for (int i = 0; i<1000; i++) {
			color = rand() % 6 + 1; // choose a color randomly
			seq[i] = color;
			len_seq++; // new color added to the sequence
			int p1_seq[101] = {0}; // the indices of the current sequence will be 1 if correct color is chosen
			int p2_seq[101] = {0}; // the indices of the current sequence will be 1 if correct color is chosen			
			// show the new color added to the sequence in the beginning of the round, once the led turns off the round starts
			if (color == 1)
				LEDBlue_On();
			else if(color == 2)
				LEDRed_On();
			else if(color == 3)
				LEDYellow_On();
			else if(color == 4)
				LEDTeal_On();
			else if(color == 5)
				LEDPurple_On();
			else
				LEDGreen_On();
			multi_delay(6);
			LED_Off();
			uart_put("Round ");
			sprintf(result, "%d", i+1);
		  uart_put(result);
			uart_put(" has begun \n\r");
			int seq_counter = 0;
			//int total = 10;
			p1_seq[seq_counter] = 1;
			p2_seq[seq_counter] = 1;
			while(seq_counter <= len_seq) {
				if ( p1_seq[seq_counter] == 0 && p2_seq[seq_counter] == 0) {
					game_break();
					delay();
					p2_won = 1; // setting p2_won doesn not mean p2_won has won as no one wins will be dispalyed on the screen, only used for the break from the for loop
					uart_put("No one has won\n\r");
					break;
				}
				// blue won
				if ( p1_pressright == 0 || p1_seq[seq_counter] == 0 ) {
					game_break();
					delay();
					p2_won = 1;
					uart_put("player 2 has won\n\r");
					break;					
				}
				// red won
				if ( p2_pressright == 0 || p2_seq[seq_counter] == 0 ) {
					game_break();
					delay();
					p1_won = 1;
					uart_put("player 1 has won\n\r");
					break;
				}
				if (seq_counter == len_seq) break;
				int ran_num = rand() % 10 + 1;
				// random delay
				for (int j = 0; j < ran_num; j++ ) {
					delay();
				}
			// randomly choose color 
				color = rand() % 6 + 1;
				if (color == seq[seq_counter]) {
					seq_counter++;
					right_choice = 1; // if color matches with the sequence, random color is the correct color
				}
				else
					right_choice = 0;
				if (color == 1)
					LEDBlue_On();
				else if(color == 2)
					LEDRed_On();
				else if(color == 3)
					LEDYellow_On();
				else if(color == 4)
					LEDTeal_On();
				else if(color == 5)
					LEDPurple_On();
				else
					LEDGreen_On();
				start.sec = current_time.sec;
				start.msec = current_time.msec;
				delay();
				LED_Off();
				delay();
				if (p1_correct == 1 ) {
						p1_seq[seq_counter] = 1;
				}
				if (p2_correct == 1) {
						p2_seq[seq_counter] = 1;
				}
		 }
			p1_correct = 0;
		  p2_correct = 0;
			uart_put("Round ");
			sprintf(result, "%d", i+1);
		  uart_put(result);
			uart_put(" has ended \n\r");	
		uart_put("\n\r");
		 if (p1_won == 1 || p2_won == 1 ) break;	
		}		
	}
	uart_put("\n\r");
	uart_put("The game has ended. Thanks for Playing.\n\r");
	uart_put(" \n\r");
	uart_put(" \n\r");
	uart_put(" \n\r");
	uart_put(" \n\r");
	while(1) {
		LEDWhite_On();
	}
}
